=== base33/Umbraco.Dexter/Dexter.Umbraco/config/dexter/indexes/schema.json
{
  "title": "JSON schema ASP.NET Core's appsettings.json file",
  "$schema": "http://json-schema.org/draft-04/schema#",

  "type": "object",

  "properties": {
    "alias": {
      "description": "Alias of the index",
      "type": "string"
    },

    "content-types": {
      "type": "array",
      "items": { "$ref": "#/definitions/content-type" }
    },

    "media-types": {
      "type": "array",
      "items": { "$ref": "#/definitions/content-type" }
    },
    "index-strategies": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Aliases of the content index strategy"
    }
  },

  "required": [ "alias" ],

  "definitions": {
    "content-type": {
      "properties": {
        "$ref": {
          "type": "string",
          "description": "Path to content type specification"
        },
        "alias": {
          "type": "string",
          "description": "Alias of the property"
        },
        "aliases": {
          "type": "array",
          "description": "Alias of the property",
          "items": {
            "type": "string"
          }
        },
        "index-all-properties": {
          "type": "boolean",
          "description": "Whether to index all properties"
        },
        "properties": {
          "type": "array",
          "items": { "$ref": "#/definitions/content-type-property" }
        },
        "index-strategies": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Aliases of the content index strategy"
        }
      },
      "type": "object"
    },

    "content-type-property": {
      "alias": {
        "type": "string",
        "description": "Alias of the property"
      },
      "exclude-field": {
        "type": "boolean",
        "description": "Whether to exclude the field from index"
      },
      "group": {
        "type": "string",
        "description": "Alias of the group"
      },
      "index-strategy": {
        "type": "string",
        "description": "Alias of the field index strategy"
      }
    }
  }
}

=== base33/Umbraco.Dexter/Dexter.Umbraco/config/dexter/indexes/example.index.json
{
  "$schema": "./schema.json",
  "alias": "example",
  "index-strategies": ["HideFromIndex"],
  "content-types": [
    {
      "alias": "contentPage",
      "index-all-properties": true,
      "properties": [
        {
          "alias": "keywords",
          "index-strategy": "CsvToWhiteSpaceStrategy"
        }
      ]
    }
  ],
  "media-types": [
    {
      "alias": "File",
      "index-all-properties": false,
      "properties": [
        {
          "alias": "umbracoFile",
          "index-strategy": "FileToTextStrategy"
        }
      ]
    }
  ]
}
